name: build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Golang 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build
        run: make
      - name: Build the Docker image
        run: docker build --tag docker.pkg.github.com/danielpacak/dev-sec-ops-seed/seed:${{ github.sha }} .
      - name: Publish the Docker image
        run: |
          echo ${{ secrets.GITHUB_PACKAGE_TOKEN }} | docker login -u danielpacak --password-stdin docker.pkg.github.com
          docker push docker.pkg.github.com/danielpacak/dev-sec-ops-seed/seed:${{ github.sha }}
      - name: Scan the Docker image with Trivy
        run: docker run --rm -e TRIVY_USERNAME=danielpacak -e TRIVY_PASSWORD=${{ secrets.GITHUB_PACKAGE_TOKEN }} aquasec/trivy docker.pkg.github.com/danielpacak/dev-sec-ops-seed/seed:${{ github.sha }}